- name: Update apt package manager
  apt:
    update_cache: yes

- name: Install common tools and networking tools
  apt:
    name:
      - curl
      - unzip
      - git
      - software-properties-common
      - wget
      - nmap
      - traceroute
      - tcpdump
      - net-tools
      - iperf3
    state: present
